modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory

[[mods]] #mandatory
	modId="polarizingbiomes" #mandatory
	version="v1.0" #mandatory
	displayName="Polarizing Biomes" #mandatory
	description='''Adds a couple winter-themed biomes.''' #mandatory
	issueTrackerURL="https://github.com/bl4ckscor3/PolarizingBiomes"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/polarizing-biomes"
	authors="bl4ckscor3"

[[dependencies.polarizingbiomes]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.polarizingbiomes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.polarizingbiomes]]
    modId="snowundertrees"
    mandatory=true
    versionRange="[v1,)"
    ordering="NONE"
    side="BOTH"